// anchors-ported.mjs — СГЕНЕРИРОВАН, руками не править.
//
// Высокоточная часть словаря кликера CGTrader (C:/cgtrader-publisher/publisher.js),
// переложенная на 25 категорий сайта. Пересобрать: scratchpad/build-ported-anchors.mjs
//
// Отбор (замерен на 16 234 карточках в Other):
//   слепой перенос всего словаря  — 9174 распознано, но ~50% ошибок
//   только вес >= 2 + чёрный список — 5837 распознано, ~80% точности  ← взято это
//
// Почему выброшены родовые списки: слова вроде stand, case, kit, holder тянули
// в containers-storage всё подряд, от глобуса до иглы для акупунктуры.
// Почему чёрный список: Kawasaki Mule уезжал в животных, Nike Lunar — в космос,
// Rheinmetall Panther — тоже в животных.
//
// Правил: 431, уникальных слов: 3090

const A = (t, c, w = 1) => ({ t, c, w });

export const PORTED = [
  A(['helicopter', 'chopper', 'helo', 'rotorcraft', 'gunship'], 'aircraft', 3),
  A(['airplane', 'aeroplane', 'airliner', 'biplane', 'seaplane', 'warplane', 'bomber', 'airbus', 'boeing', 'cessna', 'turboprop', 'orion'], 'aircraft', 2),
  A(['fighter', 'interceptor', 'stealth'], 'aircraft', 2),
  A(['grizzly', 'panda', 'lion', 'leopard', 'cheetah', 'wolf', 'fox', 'deer', 'elk', 'moose', 'horse', 'pony', 'cow', 'bull', 'ox', 'buffalo', 'bison', 'pig', 'boar', 'sheep', 'goat', 'dog', 'puppy', 'cat', 'kitten', 'rabbit', 'hare', 'elephant', 'giraffe', 'zebra', 'rhino', 'rhinoceros', 'hippo', 'hippopotamus', 'kangaroo', 'koala', 'monkey', 'ape', 'gorilla', 'chimp', 'camel', 'llama', 'alpaca', 'squirrel', 'rat', 'mouse', 'hamster', 'ferret', 'otter', 'badger', 'raccoon', 'hedgehog', 'sloth', 'armadillo', 'antelope', 'gazelle', 'warthog', 'hyena', 'cougar', 'mole', 'weasel', 'skunk', 'beaver', 'walrus', 'whale', 'narwhal', 'warhorse'], 'animals-creatures', 3),
  A(['bird', 'owl', 'parrot', 'pigeon', 'dove', 'duck', 'goose', 'swan', 'chicken', 'rooster', 'hen', 'turkey', 'penguin', 'flamingo', 'peacock', 'crow', 'raven', 'sparrow', 'robin', 'finch', 'seagull', 'gull', 'heron', 'stork', 'pelican', 'ostrich', 'toucan', 'woodpecker', 'kingfisher', 'magpie', 'vulture'], 'animals-creatures', 3),
  A(['fish', 'shark', 'goldfish', 'koi', 'tuna', 'trout', 'carp', 'catfish', 'piranha', 'clownfish', 'angelfish', 'pufferfish', 'seahorse', 'stingray', 'marlin', 'swordfish', 'barracuda', 'eel', 'snapper', 'herring', 'sardine', 'mackerel', 'crab', 'lobster', 'shrimp', 'prawn', 'octopus', 'squid', 'jellyfish', 'starfish', 'oyster', 'clam', 'mussel', 'scallop', 'conch', 'urchin', 'sturgeon', 'tilapia', 'grouper', 'halibut', 'flounder', 'anchovy', 'mahi'], 'animals-creatures', 3),
  A(['snake', 'python', 'lizard', 'gecko', 'iguana', 'chameleon', 'crocodile', 'alligator', 'turtle', 'tortoise', 'frog', 'toad', 'newt', 'salamander', 'axolotl', 'dragon', 'wyvern', 'serpent'], 'animals-creatures', 3),
  A(['dinosaur', 'trex', 'tyrannosaurus', 'velociraptor', 'triceratops', 'stegosaurus', 'brachiosaurus', 'pterodactyl', 'pteranodon', 'mosasaur', 'ankylosaurus', 'spinosaurus', 'allosaurus'], 'animals-creatures', 3),
  A(['insect', 'bug', 'ant', 'bee', 'wasp', 'hornet', 'butterfly', 'moth', 'fly', 'mosquito', 'dragonfly', 'grasshopper', 'cricket', 'cockroach', 'tarantula', 'centipede', 'ladybug', 'caterpillar', 'snail', 'worm', 'mantis', 'termite'], 'animals-creatures', 3),
  A(['truck', 'supertruck', 'lorry', 'semi truck', 'tractor trailer', 'peterbilt', 'kenworth', 'freightliner', 'dump truck', 'tanker truck', 'pickup', 'flatbed'], 'vehicles', 3),
  A(['bus', 'coach', 'minibus', 'cityliner', 'trolleybus', 'double decker', 'doubledecker'], 'vehicles', 3),
  A(['train', 'locomotive', 'tram', 'monorail', 'wagon', 'railcar', 'freight car', 'boxcar', 'subway car', 'metro car'], 'vehicles', 3),
  A(['motorcycle', 'motorbike', 'scooter', 'moped', 'chopper bike'], 'vehicles', 3),
  A(['bicycle', 'bike', 'ebike', 'cycle', 'tricycle'], 'vehicles', 2),
  A(['forklift', 'bulldozer', 'excavator', 'loader', 'backhoe', 'crane truck', 'dozer', 'grader', 'tractor', 'harvester', 'combine', 'roller', 'paver', 'skid steer', 'trencher'], 'vehicles', 3),
  A(['tank', 'apc', 'ifv', 'armored vehicle', 'armoured vehicle', 'humvee', 'mrap', 'howitzer'], 'military-vehicles', 3),
  A(['car', 'sedan', 'coupe', 'hatchback', 'convertible', 'roadster', 'automobile'], 'vehicles', 2),
  A(['suv', 'crossover', 'jeep', 'offroader'], 'vehicles', 3),
  A(['supercar', 'sportscar'], 'vehicles', 3),
  A(['camry', 'corolla', 'prius', 'rav4', 'civic', 'accord', 'golf gti', 'passat', 'sentra', 'altima', 'elantra'], 'vehicles', 3),
  A(['boat', 'ship', 'yacht', 'sailboat', 'vessel', 'ferry', 'tanker ship', 'cargo ship', 'cruise ship', 'tugboat', 'trawler', 'canoe', 'kayak', 'dinghy', 'catamaran', 'barge', 'gondola', 'schooner', 'frigate', 'destroyer', 'corvette', 'submarine', 'warship', 'lcac', 'hovercraft'], 'ships', 2),
  A(['man', 'male', 'soldier', 'warrior', 'knight', 'farmer', 'worker', 'miner', 'sailor', 'policeman', 'fireman', 'doctor', 'nurse', 'chef', 'businessman', 'gentleman', 'king', 'priest', 'monk', 'cowboy', 'pirate', 'viking', 'samurai', 'ninja', 'guard', 'hunter', 'fisherman', 'cyclist', 'runner', 'athlete', 'peasant', 'serf', 'gladiator', 'centurion', 'legionnaire', 'musketeer', 'conquistador', 'shaman', 'prisoner', 'inmate', 'convict'], 'characters-people', 2),
  A(['woman', 'female', 'girl', 'lady', 'queen', 'princess', 'witch', 'nun', 'ballerina', 'dancer', 'waitress'], 'characters-people', 2),
  A(['infant', 'newborn', 'toddler', 'boy'], 'characters-people', 2),
  A(['hand', 'arm', 'leg', 'foot', 'head', 'face', 'skull', 'torso', 'anatomy', 'muscle', 'bone', 'ribcage', 'ecorche'], 'characters-people', 2),
  A(['robot', 'cyborg', 'android', 'mech', 'droid', 'alien', 'stormtrooper', 'trooper'], 'characters-people', 2),
  A(['wizard', 'elf', 'orc', 'goblin', 'troll', 'fairy', 'angel', 'demon', 'ghost', 'monster', 'creature', 'golem', 'minotaur', 'centaur', 'clown', 'mascot', 'mummy', 'zombie', 'slimer'], 'characters-people', 2),
  A(['jacket', 'coat', 'shirt', 'tshirt', 'hoodie', 'sweater', 'pants', 'jeans', 'trousers', 'shorts', 'skirt', 'dress', 'gown', 'robe', 'suit', 'uniform', 'shoe', 'sneaker', 'boot', 'sandal', 'heel', 'glove', 'hat', 'cap', 'helmet', 'beanie', 'scarf', 'tie', 'belt', 'sock', 'wig', 'wallet', 'purse', 'handbag', 'backpack', 'sunglasses', 'goggles', 'jewelry', 'jewellery', 'necklace', 'bracelet', 'earring', 'pendant', 'brooch', 'wristwatch', 'tiara', 'anklet', 'cufflink'], 'clothing-accessories', 2),
  A(['phone', 'smartphone', 'iphone', 'cellphone'], 'electronics-gadgets', 3),
  A(['laptop', 'notebook', 'ultrabook', 'macbook', 'computer', 'pc', 'desktop', 'keyboard', 'mouse', 'monitor', 'motherboard', 'cpu', 'gpu', 'ssd', 'router', 'server', 'tablet', 'ipad'], 'electronics-gadgets', 3),
  A(['speaker', 'headphone', 'earphone', 'earbud', 'airpods', 'microphone', 'amplifier', 'soundbar', 'walkie talkie', 'radio'], 'electronics-gadgets', 3),
  A(['tv', 'television', 'camera', 'camcorder', 'projector', 'webcam'], 'electronics-gadgets', 2),
  A(['charger', 'powerbank', 'power bank', 'adapter', 'console', 'xbox', 'playstation', 'nintendo', 'joystick', 'gamepad', 'smartwatch', 'vr headset', 'atm', 'vending machine', 'printer', 'scanner', 'modem', 'led', 'circuit'], 'electronics-gadgets', 2),
  A(['chair', 'armchair', 'stool', 'recliner', 'office chair'], 'furniture-interior', 3),
  A(['table', 'desk', 'coffee table', 'dining table', 'workstation', 'nightstand'], 'furniture-interior', 3),
  A(['sofa', 'couch', 'loveseat', 'settee', 'ottoman'], 'furniture-interior', 3),
  A(['bed', 'bunk', 'mattress', 'crib', 'cot'], 'furniture-interior', 3),
  A(['cabinet', 'wardrobe', 'dresser', 'drawer', 'shelf', 'shelving', 'bookcase', 'sideboard', 'cupboard', 'bookshelf', 'filing cabinet', 'tv stand'], 'furniture-interior', 3),
  A(['lamp', 'chandelier', 'sconce', 'floor lamp', 'table lamp', 'pendant light', 'lantern'], 'lighting', 3),
  A(['fridge', 'refrigerator', 'oven', 'stove', 'microwave', 'dishwasher', 'washing machine', 'washer', 'dryer', 'freezer'], 'electronics-gadgets', 3),
  A(['bowl', 'mug', 'glassware', 'cutlery', 'teapot', 'kettle', 'saucer', 'tableware', 'dinnerware', 'wine glass'], 'kitchen-tableware', 2),
  A(['apple', 'banana', 'grape', 'strawberry', 'berry', 'berries', 'lemon', 'pear', 'mango', 'pineapple', 'watermelon', 'melon', 'kiwi', 'avocado', 'fruit'], 'food-beverages', 3),
  A(['carrot', 'potato', 'tomato', 'onion', 'pepper', 'broccoli', 'cabbage', 'lettuce', 'cucumber', 'mushroom', 'corn', 'pumpkin', 'garlic', 'vegetable', 'eggplant', 'zucchini'], 'food-beverages', 3),
  A(['wine', 'beer', 'coffee', 'tea', 'juice', 'soda', 'cocktail', 'whiskey', 'whisky', 'scotch', 'bourbon', 'tequila', 'vodka', 'champagne', 'beverage', 'drink', 'milk', 'coca cola', 'coca-cola', 'pepsi', 'sprite', 'fanta', 'lemonade', 'sparkling water', 'energy drink'], 'food-beverages', 3),
  A(['bread', 'burger', 'pizza', 'sandwich', 'cake', 'cookie', 'donut', 'pastry', 'croissant', 'sushi', 'pasta', 'noodle', 'steak', 'meat', 'cheese', 'egg', 'caviar', 'candy', 'icecream', 'soup', 'salad', 'food'], 'food-beverages', 2),
  A(['flower', 'rose', 'tulip', 'daisy', 'sunflower', 'lily', 'orchid', 'magnolia', 'lotus', 'peony', 'hibiscus', 'bouquet', 'blossom', 'bloom'], 'nature-plants', 3),
  A(['pine', 'spruce', 'fir', 'cedar', 'cypress', 'conifer'], 'nature-plants', 3),
  A(['tree', 'plant', 'bush', 'shrub', 'fern', 'grass', 'palm', 'cactus', 'succulent', 'vine', 'ivy', 'leaf', 'foliage', 'hedge', 'moss'], 'nature-plants', 2),
  A(['rifle', 'pistol', 'revolver', 'shotgun', 'gun', 'handgun', 'carbine', 'sniper', 'machine gun', 'smg', 'firearm', 'ak47', 'ak-47', 'm16', 'glock'], 'weapons-tools', 3),
  A(['sword', 'knife blade', 'dagger', 'axe', 'spear', 'mace', 'katana', 'machete', 'saber', 'sabre', 'halberd', 'crossbow', 'bow', 'melee', 'brass knuckles', 'knuckle duster', 'nunchaku', 'brass knuckle'], 'weapons-tools', 3),
  A(['missile', 'rocket', 'warhead', 'grenade', 'bomb', 'artillery shell'], 'military-vehicles', 3),
  A(['armor', 'armour', 'shield', 'bulletproof', 'flak', 'kevlar', 'body armor'], 'clothing-accessories', 2),
  A(['machine', 'engine', 'motor', 'generator', 'turbine', 'compressor', 'pump', 'conveyor', 'press', 'lathe', 'mill', 'cnc', 'substation', 'transformer', 'reactor', 'boiler', 'baler', 'compactor', 'shredder', 'crusher', 'derrick', 'oil rig', 'drilling rig', 'oil platform'], 'industrial-equipment', 2),
  A(['gear', 'bearing', 'valve', 'pipe fitting', 'bolt', 'screw', 'nut', 'flange', 'coupling', 'bracket', 'piston', 'shaft', 'spring', 'wheel', 'tire', 'rim', 'hubcap'], 'industrial-equipment', 2),
  A(['drill', 'hammer', 'wrench', 'screwdriver', 'pliers', 'saw', 'grinder', 'sander', 'welder', 'toolbox', 'power tool'], 'industrial-equipment', 2),
  A(['knife', 'spatula', 'whisk', 'grater', 'peeler', 'cutting board', 'ladle', 'colander', 'strainer', 'can opener', 'corkscrew'], 'kitchen-tableware', 2),
  A(['shovel', 'spade', 'rake', 'pickaxe', 'pitchfork', 'crowbar'], 'weapons-tools', 2),
  A(['microscope', 'beaker', 'flask', 'test tube', 'pipette', 'centrifuge', 'bunsen', 'petri', 'lab equipment'], 'industrial-equipment', 3),
  A(['syringe', 'scalpel', 'stethoscope', 'pill', 'capsule', 'vitamin', 'medicine', 'bandage', 'wheelchair', 'crutch', 'xray', 'x-ray', 'prosthetic', 'implant', 'forceps', 'suture', 'surgical', 'defibrillator', 'iv drip'], 'medical-3d-models', 3),
  A(['football', 'soccer ball', 'basketball', 'baseball', 'tennis', 'golf club', 'hockey', 'skateboard', 'surfboard', 'snowboard', 'dumbbell', 'barbell', 'treadmill', 'yoga mat', 'racket', 'racquet', 'boxing glove', 'bowling', 'dartboard'], 'sports-recreation', 2),
  A(['guitar', 'piano', 'drum', 'violin', 'trumpet', 'saxophone', 'flute', 'cello', 'harp', 'banjo', 'ukulele', 'accordion'], 'musical-instruments', 3),
  A(['toy', 'lego', 'doll', 'teddy', 'figurine', 'rubber duck', 'dice', 'puzzle', 'board game'], 'toys-games', 2),
  A(['spaceship', 'spacecraft', 'starship', 'ufo', 'space shuttle', 'alien ship'], 'space-scifi', 3),
  A(['planet', 'asteroid', 'comet', 'meteor'], 'space-scifi', 3),
  A(['satellite', 'space station', 'astronaut', 'cosmonaut', 'nebula', 'lunar module', 'space capsule', 'space probe', 'mars rover', 'lunar lander', 'orbiter', 'launch vehicle'], 'space-scifi', 3),
  A(['apache', 'blackhawk', 'black hawk', 'chinook', 'aw101', 'mi-8', 'mi-17', 'mi-24', 'ka-52'], 'aircraft', 3),
  A(['diamond', 'gemstone', 'gem', 'ruby', 'sapphire', 'emerald', 'crystal gem', 'jewel'], 'clothing-accessories', 2),
  A(['van', 'minivan', 'cargo van', 'panel van', 'box truck', 'ambulance', 'hearse', 'limousine', 'limo', 'snowplow', 'snowplough', 'trailer', 'caravan', 'camper', 'motorhome', 'rv', 'fire truck', 'garbage truck', 'tow truck', 'delivery truck'], 'vehicles', 3),
  A(['carriage', 'stagecoach', 'chariot', 'wagon cart', 'horse cart', 'handcart', 'pushcart', 'rickshaw', 'wheelbarrow'], 'vehicles', 2),
  A(['go kart', 'go-kart', 'kart', 'atv', 'quad bike', 'snowmobile', 'golf cart', 'buggy'], 'vehicles', 3),
  A(['crop sprayer', 'seeder', 'plough', 'plow', 'combine harvester', 'cultivator', 'agrifac'], 'vehicles', 3),
  A(['agusta', 'agustawestland', 'sikorsky', 'eurocopter', 'robinson r44', 'bell 206', 'bell 407', 'airwolf', 'pave low'], 'aircraft', 3),
  A(['learjet', 'gulfstream', 'bombardier', 'embraer', 'mirage', 'rafale', 'eurofighter', 'tornado jet', 'harrier', 'spitfire', 'messerschmitt', 'lancaster bomber', 'viper jet', 'phantom jet', 'hornet jet', 'tomcat', 'mig', 'sukhoi', 'su-27', 'su-57', 'f-16', 'f-18', 'f-22', 'f-35'], 'aircraft', 3),
  A(['drone', 'uav', 'mohajer', 'bayraktar', 'reaper drone', 'predator drone', 'quadrocopter'], 'aircraft', 2),
  A(['rattlesnake', 'anaconda', 'boa', 'mamba', 'adder', 'rattler', 'king cobra'], 'animals-creatures', 3),
  A(['langouste', 'crayfish', 'crawfish', 'krill', 'barnacle'], 'animals-creatures', 3),
  A(['canis', 'lupus', 'coyote', 'dingo', 'jackal'], 'animals-creatures', 3),
  A(['argema', 'luna moth', 'scolopendra', 'millipede', 'cicada', 'locust', 'earwig', 'silverfish', 'firefly'], 'animals-creatures', 3),
  A(['hazelnut', 'walnut', 'almond', 'chestnut', 'acorn', 'pinecone', 'pine cone', 'venus flytrap', 'flytrap', 'dionaea', 'aloe', 'bamboo stalk', 'reed plant', 'barley', 'corn stalk'], 'nature-plants', 3),
  A(['pomegranate', 'fig fruit', 'date fruit', 'apricot', 'nectarine', 'coconut', 'papaya', 'guava', 'lychee', 'persimmon'], 'food-beverages', 3),
  A(['french fry', 'french fries', 'fries', 'sauce', 'pesto', 'ketchup', 'mayonnaise', 'jam jar', 'sugar packet', 'salt shaker', 'spice jar', 'pretzel', 'bagel'], 'food-beverages', 2),
  A(['nikon', 'canon eos', 'sony camera', 'dslr', 'camcorder', 'gopro', 'polaroid'], 'electronics-gadgets', 3),
  A(['calculator', 'blu ray', 'blu-ray', 'dvd', 'cd disc', 'disc player', 'walkman', 'cassette player', 'stadia', 'game controller', 'remote control', 'tv remote', 'laser level', 'weather station', 'barcode scanner', 'cash register', 'pos terminal'], 'electronics-gadgets', 2),
  A(['lute', 'xylophone', 'keytar', 'mandolin', 'sitar', 'tambourine', 'maracas', 'bagpipe', 'harmonica', 'kazoo', 'clarinet', 'oboe', 'tuba', 'trombone', 'french horn', 'bongo', 'conga', 'marimba', 'synthesizer', 'turntable', 'dj mixer'], 'musical-instruments', 3),
  A(['shin pad', 'shin guard', 'mouthguard', 'cleats', 'jersey', 'sports jersey', 'whistle', 'medal', 'trophy', 'kettlebell', 'punching bag', 'penalty card', 'racing flag', 'checkered flag', 'goal post', 'hurdle', 'javelin', 'discus', 'shot put'], 'sports-recreation', 2),
  A(['sportswear', 'tracksuit', 'swimsuit', 'bikini', 'lingerie', 'apron', 'poncho', 'kimono', 'cape', 'cloak', 'mitten', 'headband', 'wristband', 'watch band', 'watch strap', 'solo loop', 'stocking'], 'clothing-accessories', 2),
  A(['trebuchet', 'catapult', 'ballista', 'cannon', 'artillery', 'detonator', 'landmine', 'land mine', 'parachute', 'ordnance', 'warhead', 'patriot missile', 's-400', 's-300', '2s7', 'pion'], 'military-vehicles', 3),
  A(['caduceus', 'oximeter', 'thermal cycler', 'pcr', 'spine fixation', 'orthopedic', 'dental unit', 'x ray unit', 'iv bag', 'iv fluid', 'catheter', 'tourniquet', 'microtome', 'autoclave'], 'medical-3d-models', 3),
  A(['rebar', 'drilling rig', 'clarifier', 'silo', 'grain storage', 'bollard', 'steel cable', 'wire rope', 'ducting', 'duct', 'hvac', 'gearbox', 'loom', 'offshore', 'pipeline', 'scaffold', 'manifold', 'actuator', 'hydraulic cylinder', 'conveyor belt'], 'industrial-equipment', 2),
  A(['stonehenge', 'pyramid', 'ziggurat', 'amphitheater', 'amphitheatre', 'colosseum', 'obelisk', 'aqueduct', 'archway', 'architrave', 'frieze', 'cornice', 'park bench', 'prison cell', 'jail cell', 'sauna', 'pergola', 'gazebo', 'distribution center', 'fulfillment center'], 'architecture-landmarks', 2),
  A(['extravehicular', 'mobility unit', 'cosmodrome', 'spaceport', 'launch complex', 'space base'], 'space-scifi', 3),
  A(['traffic light', 'stop light', 'taxi light', 'street light', 'lamppost', 'lamp post', 'fire bell', 'alarm bell', 'neon sign', 'road sign'], 'architecture-landmarks', 2),
  A(['toilet', 'sink', 'washbasin', 'wash basin', 'bathtub', 'bath tub', 'shower', 'bidet', 'urinal', 'hot tub', 'jacuzzi', 'faucet', 'toilet seat'], 'electronics-gadgets', 2),
  A(['sdram', 'sodimm', 'dimm', 'hdd', 'hard drive', 'solid state drive', 'ethernet cable', 'rj45', 'fiber optic', 'network cable', 'usb cable', 'hdmi cable', 'power cord', 'extension cord', 'circuit board', 'pcb', 'heatsink', 'cooling fan', 'power supply', 'graphics card'], 'electronics-gadgets', 3),
  A(['copier', 'photocopier', 'vhs', 'jukebox', 'cdj', 'dj player', 'pioneer cdj', 'ps5', 'ps4', 'game box', 'record player', 'gramophone', 'phonograph'], 'electronics-gadgets', 2),
  A(['vinyl record', 'vinyl album', 'vinyl', 'record album', 'lp record'], 'musical-instruments', 2),
  A(['stinger', 'fim-92', 'javelin missile', 'sam system', 'abrams', 'leopard tank', 'challenger tank', 't-90', 't-72', 't-80', 'bradley', 'leclerc'], 'military-vehicles', 3),
  A(['parasaurolophus', 'diplodocus', 'apatosaurus', 'iguanodon', 'carnotaurus', 'gallimimus', 'compsognathus', 'dilophosaurus', 'deinonychus'], 'animals-creatures', 3),
  A(['bullfrog', 'tree frog', 'poison frog', 'tadpole', 'komodo', 'monitor lizard', 'skink'], 'animals-creatures', 3),
  A(['ryegrass', 'lawn grass', 'turf', 'meadow grass', 'pampas grass'], 'nature-plants', 3),
  A(['lavender', 'daffodil', 'carnation', 'chrysanthemum', 'marigold', 'poppy', 'iris flower', 'dahlia', 'azalea', 'camellia', 'gardenia', 'jasmine'], 'nature-plants', 3),
  A(['bamboo grove', 'palm tree', 'oak tree', 'maple tree', 'willow', 'birch', 'banyan', 'baobab', 'sequoia', 'redwood'], 'nature-plants', 2),
  A(['golf bag', 'waterski', 'water ski', 'wakeboard', 'ski pole', 'snorkel', 'flippers', 'diving fin', 'life jacket', 'life vest', 'buoyancy'], 'sports-recreation', 2),
  A(['dome tent', 'cabin tent', 'camping tent', 'pop up tent', 'teepee', 'tipi', 'marquee tent', 'canopy tent'], 'sports-recreation', 3),
  A(['spaceplane', 'spaceshiptwo', 'space plane', 'reusable rocket', 'falcon 9', 'starship rocket'], 'space-scifi', 3),
  A(['hot air balloon', 'airship balloon', 'weather balloon'], 'aircraft', 3),
  A(['crown', 'scepter', 'sceptre', 'regalia', 'orb royal', 'coronet', 'diadem', 'laurel wreath'], 'clothing-accessories', 2),
  A(['ice cube', 'ice cubes', 'ice tray'], 'food-beverages', 2),
  A(['maneki neko', 'lucky cat', 'bobblehead', 'action figure', 'collectible figure', 'nendoroid', 'funko'], 'toys-games', 2),
  A(['grim reaper', 'skeleton warrior', 'lich', 'banshee', 'wraith', 'specter', 'poltergeist', 'reaper'], 'characters-people', 2),
  A(['firefighter', 'fireman', 'paramedic', 'riot police', 'swat', 'commando', 'marine soldier', 'navy seal', 'ranger soldier'], 'characters-people', 2),
  A(['truss', 'girder', 'steel beam', 'i-beam', 'scaffold tower', 'crane jib', 'gantry', 'derrick crane', 'port crane', 'tower crane'], 'industrial-equipment', 2),
  A(['endoscope', 'vaccine', 'virus', 'bacteria', 'coronavirus', 'covid', 'dna', 'chromosome', 'neuron', 'cornea', 'retina', 'ovary', 'uterus', 'placenta', 'sperm', 'plasma', 'nebulizer', 'inhaler', 'ampoule', 'vial', 'infusion'], 'medical-3d-models', 3),
  A(['oscilloscope', 'multimeter', 'encryptor', 'encryption machine', 'rotor machine'], 'electronics-gadgets', 3),
  A(['telescope', 'observatory'], 'space-scifi', 2),
  A(['tumbleweed', 'seaweed', 'algae', 'lichen', 'sapling', 'driftwood'], 'nature-plants', 3),
  A(['petal'], 'nature-plants', 3),
  A(['iceberg', 'glacier', 'dune', 'canyon', 'waterfall', 'geyser', 'coral reef'], 'architecture-landmarks', 3),
  A(['subnotebook', 'netbook', 'plotter'], 'electronics-gadgets', 3),
  A(['barcode', 'kiosk', 'terminal', 'smoke detector', 'siren', 'strobe', 'alarm'], 'electronics-gadgets', 3),
  A(['ethernet', 'hdmi', 'lcd', 'oled', 'transistor', 'capacitor', 'resistor', 'plug', 'socket outlet'], 'electronics-gadgets', 2),
  A(['cassette'], 'electronics-gadgets', 3),
  A(['spaghetti', 'salami', 'cinnamon', 'jam', 'whipped cream', 'fried egg', 'peanut butter', 'chewing gum'], 'food-beverages', 3),
  A(['raspberry', 'blueberry'], 'food-beverages', 3),
  A(['cola', 'espresso', 'cappuccino'], 'food-beverages', 3),
  A(['poster', 'placard', 'pennant', 'garland', 'wreath', 'plaque', 'confetti', 'streamer', 'medallion', 'flag', 'signboard', 'banner sign'], 'signage-decor', 3),
  A(['colonnade', 'balustrade', 'terrace', 'chimney', 'snowflake', 'icicle'], 'signage-decor', 2),
  A(['pulley', 'crankshaft', 'camshaft', 'condenser', 'nozzle', 'caster wheel', 'swivel caster'], 'industrial-equipment', 3),
  A(['headlight', 'taillight', 'radiator'], 'industrial-equipment', 2),
  A(['hydrant', 'sprinkler', 'radar'], 'industrial-equipment', 2),
  A(['silo container'], 'industrial-equipment', 3),
  A(['lighthouse', 'windmill', 'watermill'], 'architecture-landmarks', 3),
  A(['petrol station', 'gas station', 'tunnel', 'kiosk building'], 'architecture-landmarks', 3),
  A(['silo building'], 'architecture-landmarks', 3),
  A(['elevator', 'escalator'], 'furniture-interior', 3),
  A(['trilobite', 'anemone', 'slug'], 'animals-creatures', 3),
  A(['seal animal', 'mammoth'], 'animals-creatures', 3),
  A(['larva', 'cocoon'], 'animals-creatures', 3),
  A(['seashell'], 'animals-creatures', 2),
  A(['apollo', 'skylab', 'soyuz', 'orbiter', 'lunar module', 'mars rover', 'space probe'], 'space-scifi', 3),
  A(['toaster', 'juicer', 'cooker', 'food mixer', 'coffee grinder'], 'electronics-gadgets', 3),
  A(['thermos', 'lunchbox'], 'kitchen-tableware', 3),
  A(['radiator heater'], 'electronics-gadgets', 3),
  A(['satchel', 'loafer', 'stiletto', 'shoelace'], 'clothing-accessories', 3),
  A(['sled', 'toboggan', 'kayak paddle', 'punchbag', 'shinpad'], 'sports-recreation', 3),
  A(['yoga'], 'sports-recreation', 2),
  A(['biathlete', 'biathlonist'], 'characters-people', 3),
  A(['lightbulb', 'floodlight', 'spotlight', 'neon', 'light bulb'], 'signage-decor', 3),
  A(['bulb'], 'signage-decor', 2),
  A(['beanbag'], 'furniture-interior', 3),
  A(['console table'], 'furniture-interior', 3),
  A(['ampoule box'], 'medical-3d-models', 3),
  A(['crane bird', 'whooping crane', 'sandhill crane'], 'animals-creatures', 3),
  A(['dragon fruit', 'dragonfruit'], 'food-beverages', 3),
  A(['tesla coil'], 'industrial-equipment', 3),
  A(['tie down', 'tie-down', 'cap screw', 'cap bolt', 'belt conveyor', 'belt drive', 'timing belt', 'v-belt', 'conveyor belt'], 'industrial-equipment', 3),
  A(['down jacket', 'goose down jacket', 'puffer jacket'], 'clothing-accessories', 3),
  A(['toyota', 'volkswagen', 'vw ', 'mercedes', 'bmw', 'audi', 'ford', 'chevrolet', 'chevy', 'nissan', 'honda', 'mazda', 'subaru', 'hyundai', 'kia', 'lexus', 'alfa romeo', 'fiat', 'peugeot', 'renault', 'skoda', 'volvo', 'tesla model', 'tesla car', 'dodge', 'chrysler', 'cadillac', 'buick', 'jaguar car', 'land rover', 'mini cooper', 'mitsubishi', 'suzuki', 'opel', 'seat ', 'citroen', 'infiniti', 'acura', 'genesis car', 'ae86', 'trueno', 'stelvio', 'camaro', 'corvette'], 'vehicles', 3),
  A(['samsung galaxy', 'galaxy s', 'iphone', 'ipad', 'airpods', 'apple watch', 'smartwatch', 'smart watch', 'sony smartwatch', 'talkboy', 'cassette recorder', 'xbox', 'playstation', 'nintendo', 'kindle', 'smartphone', 'galaxy note'], 'electronics-gadgets', 3),
  A(['c-47', 'skytrain', 'spacejet', 'douglas dc', 'sport plane', 'cargo plane', 'vintage plane', 'fighter plane', 'warplane'], 'aircraft', 3),
  A(['raven', 'crow', 'robin bird', 'finch', 'magpie', 'seagull', 'swan', 'goose', 'heron', 'stork', 'woodpecker', 'kingfisher', 'peacock'], 'animals-creatures', 3),
  A(['goldfish', 'koi', 'piranha', 'catfish', 'stingray', 'ray fish', 'bathyraja', 'manta', 'marlin', 'swordfish', 'barracuda'], 'animals-creatures', 3),
  A(['frog', 'toad', 'poison dart frog', 'newt', 'salamander', 'axolotl'], 'animals-creatures', 3),
  A(['chimpanzee', 'chimp', 'stoat', 'weasel', 'otter', 'badger', 'raccoon', 'hedgehog', 'mole', 'bat animal', 'hyena', 'cougar', 'meerkat', 'sloth', 'armadillo', 'anteater', 'possum', 'wombat', 'platypus', 'antelope', 'gazelle', 'bison', 'moose', 'elk', 'boar', 'warthog', 'tapir', 'okapi', 'wildebeest'], 'animals-creatures', 3),
  A(['naga', 'dragon', 'wyvern', 'hydra', 'griffin', 'phoenix', 'kraken', 'basilisk'], 'animals-creatures', 3),
  A(['ichthyosaur', 'plesiosaur', 'pterodactyl', 'pteranodon', 'mosasaur', 'ammonite'], 'animals-creatures', 3),
  A(['bathrobe', 'necktie', 'bow tie', 'socks', 'bandana', 'headband', 'suitcase', 'straitjacket', 'fishing hat', 'khaki hat', 'beanie', 'baseball cap', 'scarf', 'mitten', 'wristband', 'apron', 'poncho', 'kimono', 'sari', 'turban', 'fedora', 'beret', 'helmet and mask', 'balaclava', 'vest', 'blazer', 'sweater', 'pajama', 'underwear', 'bikini', 'swimsuit', 'lingerie', 'corset', 'tuxedo', 'jumpsuit', 'raincoat', 'windbreaker', 'parka', 'down jacket', 'winter jacket', 'leather jacket'], 'clothing-accessories', 3),
  A(['cartridge', 'bullet', 'shell casing', 'ammo box', 'magazine clip', 'sabre', 'saber', 'rapier', 'tomahawk', 'halberd', 'glaive', 'flail', 'crossbow', 'longbow', 'lightsaber', 'blaster', 'airsoft', 'paintball gun'], 'weapons-tools', 3),
  A(['hockey', 'boxing glove', 'boxing', 'mma glove', 'punching bag', 'treadmill', 'exercise bike', 'weight plate', 'yoga mat', 'jump rope', 'climbing', 'surfboard', 'paddle', 'racket', 'racquet', 'frisbee', 'bowling', 'dartboard', 'pool table', 'billiard', 'ping pong', 'table tennis'], 'sports-recreation', 3),
  A(['tower crane', 'crane truck', 'overhead crane', 'gantry crane', 'pallet jack', 'pallet truck', 'forklift', 'scissor lift', 'mast lift', 'boom lift', 'aerial lift', 'hoist', 'winch', 'jack stand', 'conveyor belt', 'mixer truck', 'cement mixer', 'concrete mixer', 'compactor', 'jackhammer', 'scaffolding', 'scaffold', 'generator set', 'air compressor', 'water pump', 'hydraulic press', 'injection molding', '3d printer', 'cnc machine', 'lathe machine', 'milling machine', 'wood chipper', 'log splitter', 'wheel loader', 'skid steer', 'backhoe', 'trencher', 'paver', 'road roller', 'grader'], 'industrial-equipment', 3),
  A(['croissant', 'baguette', 'pretzel', 'bagel', 'muffin', 'cupcake', 'pie', 'tart', 'pancake', 'waffle', 'crepe', 'dumpling', 'taco', 'burrito', 'nachos', 'hotdog', 'hot dog', 'noodle', 'ramen', 'curry', 'kebab', 'falafel', 'hummus', 'yogurt', 'ice cream cone', 'popsicle', 'lollipop', 'candy', 'macaron', 'tiramisu', 'pudding', 'jelly', 'marshmallow', 'popcorn'], 'food-beverages', 3),
  A(['helmet', 'mask', 'balaclava', 'respirator', 'face shield', 'hard hat', 'safety helmet', 'motorcycle helmet', 'bike helmet', 'ski helmet', 'diving mask', 'gas mask'], 'clothing-accessories', 3),
  A(['gloves', 'boots', 'shoes', 'sneaker', 'sandal', 'slipper', 'clogs', 'loafers', 'heels', 'uniform', 'suit', 'clothes', 'clothing', 'glasses', 'sunglasses', 'goggles', 'belt', 'tie', 'scarf', 'hat', 'cap', 'beanie', 'bandana', 'jacket', 'coat', 'shirt', 'pants', 'jeans', 'shorts', 'skirt', 'dress', 'gown', 'robe', 'socks', 'stockings'], 'clothing-accessories', 3),
  A(['worker', 'construction worker', 'factory worker', 'warehouse worker', 'laborer'], 'characters-people', 3),
  A(['infant', 'newborn', 'toddler'], 'characters-people', 3),
  A(['human hand', 'human head', 'human face', 'severed hand', 'realistic hand', 'realistic head', 'male head', 'female head', 'human skin'], 'characters-people', 3),
  A(['fighter jet', 'fighter aircraft', 'stealth fighter', 'jet fighter', 'combat jet', 'interceptor'], 'aircraft', 3),
  A(['emoji', 'emoticon', 'cartoon character', 'cartoon face', 'smiley'], 'characters-people', 3),
  A(['airport', 'airport terminal', 'train station', 'bus station', 'gas station', 'metro station', 'fire station', 'police station', 'power station'], 'architecture-landmarks', 3),
  A(['road sign', 'traffic sign', 'street sign', 'signboard', 'billboard', 'neon sign', 'shop sign'], 'architecture-landmarks', 3),
  A(['kitchen interior', 'kitchen room', 'modular kitchen', 'fitted kitchen'], 'furniture-interior', 3),
  A(['construction', 'scaffolding', 'building site', 'construction site'], 'architecture-landmarks', 3),
  A(['wheel', 'tire', 'tyre', 'rim', 'hubcap', 'wheel and tire'], 'industrial-equipment', 3),
  A(['smart home', 'smart device', 'smart hub', 'iot device'], 'electronics-gadgets', 3),
  A(['led panel', 'led strip', 'led module', 'led display', 'light panel'], 'electronics-gadgets', 3),
  A(['starfish', 'sea star', 'star fish'], 'animals-creatures', 3),
  A(['moorish idol', 'tropical fish', 'angelfish', 'butterflyfish', 'tang fish', 'wrasse'], 'animals-creatures', 3),
  A(['bird of paradise flower', 'strelitzia', 'flower in vase', 'bouquet', 'flower arrangement'], 'nature-plants', 3),
  A(['pickup', 'four-door pickup', 'all-terrain pickup', 'crew cab', 'double cab', 'pickup truck'], 'vehicles', 3),
  A(['landing ship', 'landing craft', 'amphibious ship', 'corvette', 'frigate', 'destroyer', 'icebreaker ship', 'rescue ship'], 'ships', 3),
  A(['pedal car', 'toy car', 'ride-on car', 'kids car', 'childs roadster'], 'toys-games', 3),
  A(['skeleton of', 'dog skeleton', 'horse skeleton', 'animal skeleton', 'skeleton anatomy'], 'animals-creatures', 3),
  A(['sailor', 'us navy sailor', 'navy sailor', 'naval officer', 'seaman'], 'characters-people', 3),
  A(['crash test dummy', 'crash dummy', 'test dummy'], 'characters-people', 3),
  A(['ronald mcdonald', 'charlie brown', 'clown', 'leprechaun', 'mascot'], 'characters-people', 3),
  A(['road cyclist', 'cyclist', 'runner athlete'], 'characters-people', 3),
  A(['steam engine', 'flywheel engine', 'rocket engine', 'jet engine display', 'stirling engine'], 'industrial-equipment', 3),
  A(['laser cutting machine', 'sheet metal laser', 'laser cutter', 'plasma cutter', 'cnc router'], 'industrial-equipment', 3),
  A(['electrical substation', 'substation', 'transformer station', 'power substation'], 'industrial-equipment', 3),
  A(['pipe stand', 'vevor pipe', 'adjustable jack', 'adjustable stand', 'folding stand', 'depth gauge', 'vernier', 'mitutoyo', 'caliper gauge'], 'weapons-tools', 3),
  A(['fishing rod', 'fishing reel', 'fly reel', 'fly fishing', 'spinning reel', 'baitcaster', 'tackle'], 'sports-recreation', 3),
  A(['wah pedal', 'flanger', 'phaser pedal', 'distortion pedal', 'overdrive pedal', 'guitar pedal', 'effects pedal', 'boss bf', 'delay pedal', 'reverb pedal'], 'musical-instruments', 3),
  A(['suture practice', 'suture kit', 'bone curette', 'bone holder', 'iris scissors', 'surgical scissors', 'sea urchin scissors', 'curette', 'ollier', 'volkmann'], 'medical-3d-models', 3),
  A(['champignon', 'mushroom pile', 'portobello', 'shiitake', 'oyster mushroom'], 'food-beverages', 3),
  A(['oyster shell', 'oyster', 'clam shell', 'mussel', 'scallop shell', 'seashell', 'sea shell', 'conch'], 'animals-creatures', 3),
  A(['home theater seating', 'theater seating', 'recliner seating', 'cinema seating', 'paired seating'], 'furniture-interior', 3),
  A(['top hat', 'leprechaun hat', 'carnival hat', 'umbrella hat', 'felt hat', 'bowler hat', 'panama hat', 'fedora'], 'clothing-accessories', 3),
  A(['atm', 'atm machine', 'cash machine', 'cash dispenser', 'ticket machine', 'vending machine'], 'electronics-gadgets', 3),
  A(['gas cooker', 'gas stove', 'camp stove', 'camping stove', 'butane', 'portable stove', 'single burner', 'gas canister', 'gas cylinder', 'refill cylinder'], 'kitchen-tableware', 3),
  A(['rosemary', 'thyme', 'oregano', 'sage herb', 'mint leaves', 'cilantro', 'coriander'], 'nature-plants', 3),
  A(['coconut', 'coconut half'], 'food-beverages', 3),
  A(['shipping container', 'iso container', 'cargo container', 'freight container', 'marine container', 'storage container 20ft', '20ft', '40ft container'], 'industrial-equipment', 3),
  A(['air conditioner', 'portable ac', 'mini ac', 'ac unit', 'hvac unit', 'split ac'], 'electronics-gadgets', 3),
  A(['tripod', 'mini tripod', 'camera tripod', 'flexible tripod'], 'electronics-gadgets', 3),
  A(['rolling ruler', 'ruler', 'measuring tape', 'tape measure', 'protractor'], 'weapons-tools', 3),
  A(['centaur', 'minotaur', 'satyr', 'faun', 'griffin creature'], 'characters-people', 3),
  A(['fire hose', 'fire extinguisher', 'fire hydrant', 'hose reel'], 'industrial-equipment', 3),
  A(['ice tongs', 'serving tongs', 'ice bucket', 'ice container', 'champagne bucket'], 'kitchen-tableware', 3),
  A(['napkin', 'folded napkin', 'table napkin', 'serviette'], 'kitchen-tableware', 3),
  A(['high school', 'shopping mall', 'shopping complex', 'conservatory', 'winter garden', 'grocery store', 'sculptor workshop', 'foresters workspace'], 'architecture-landmarks', 3),
  A(['zeekr', 'crossover black', 'electric crossover', 'off-road pickup', 'pickup black'], 'vehicles', 3),
  A(['petra', 'al-khazneh', 'temple ruins', 'ancient temple'], 'architecture-landmarks', 3),
  A(['candelabra', 'candelabrum', 'candle holder', 'candlestick'], 'lighting', 3),
  A(['light switch', 'switch panel', 'dimmer', 'wall switch', 'outlet panel', 'power outlet'], 'electronics-gadgets', 3),
  A(['happy meal', 'mcdonalds'], 'food-beverages', 3),
  A(['ak 47', 'ak47', 'ak-47', 'ak 74', 'akm', 'kalashnikov', 'm16', 'm4a1', 'ar-15', 'ar 15', 'glock', 'beretta', 'uzi', 'mp5', 'rpg', 'rocket propelled', 'sniper', 'carbine', 'musket', 'flintlock', 'blunderbuss', 'derringer', 'luger', 'magnum', 'colt', 'winchester', 'remington', 'mossberg', 'sig sauer', 'desert eagle', 'revolver', 'handgun', 'pistol', 'rifle', 'shotgun', 'firearm', 'submachine', 'machine gun'], 'weapons-tools', 3),
  A(['brake disc', 'brake rotor', 'brake caliper', 'brake pad', 'brake drum', 'alloy wheel', 'alloy rim', 'wheel rim', 'tire rim', 'brake disk', 'rotor with', 'caliper', 'in-wheel', 'in-hub', 'drive assembly', 'driveshaft', 'drive shaft', 'stabilizer bushing', 'coil spring', 'leaf spring', 'shock absorber', 'suspension', 'cv joint', 'wheel hub', 'tire with'], 'industrial-equipment', 3),
  A(['chronograph', 'wristwatch', 'wrist watch', 'tag heuer', 'rolex', 'omega watch', 'seiko', 'casio', 'smartwatch', 'apple watch', 'pocket watch'], 'electronics-gadgets', 3),
  A(['wall clock', 'tower clock', 'turret clock', 'grandfather clock', 'cuckoo clock', 'alarm clock', 'clock dial', 'clock mechanism', 'clock tower drive'], 'lighting', 3),
  A(['huawei', 'xiaomi', 'oneplus', 'oppo', 'vivo', 'pixel phone', 'galaxy s', 'galaxy note', 'redmi', 'honor phone', 'realme'], 'electronics-gadgets', 3),
  A(['morgue', 'mortuary', 'courtroom', 'court room', 'courthouse', 'tavern interior', 'pharmacy', 'pharmacy store', 'padded cell', 'circus interior', 'gallery interior', 'art gallery', 'subway station interior', 'parking lot interior', 'parking garage', 'safe room', 'bank safe', 'squash gym', 'gym interior', 'public toilet interior', 'multiroom', 'shelter interior', 'workshop setup', 'workplace', 'indoor unit', 'vascular surgeon workplace'], 'furniture-interior', 3),
  A(['hiv virus', 'virus model', 'virus cross', 'virus structure', 'kidney model', 'kidney disease', 'polycystic', 'anatomical model', 'anatomical structure', 'teaching model', 'skull teaching', 'fetal skull', 'pediatric skull', 'manikin', 'simulation manikin', 'airway simulation', 'phoropter', 'capnograph', 'capnographis', 'seismograph', 'ilizarov', 'orthopedic apparatus', 'urine sample', 'sharps disposal', 'artery in cross', 'vein in cross', 'lymphatic massager', 'tracheostomy', 'sterile', 'biohazard', 'medstor', 'sample container', 'diseased', 'healthy and poly'], 'medical-3d-models', 3),
  A(['quantum processor', 'majorana', 'development board', 'arm-based', 'colorchecker', 'color calibration', 'calibration chart', 'calibrite', 'ozone detector', 'ozone gas', 'esd tweezer', 'discharge testing', 'high voltage'], 'industrial-equipment', 3),
  A(['spacesuit', 'space suit', 'moon spacesuit', 'nebula rocket', 'space rocket', 'launch platform', 'launch pad', 'odyssey', 'aerospace nebula', 'next generation space'], 'space-scifi', 3),
  A(['opossum', 'possum', 'walrus', 'odobenus', 'cockroach', 'coconut crab', 'parrotfish', 'parrot fish', 'fawn', 'raspberry with fur', 'pearl in', 'pearl shell'], 'animals-creatures', 3),
  A(['parrotfish', 'clownfish', 'angelfish', 'pufferfish', 'lionfish', 'swordfish'], 'animals-creatures', 3),
  A(['cockroach', 'roach', 'centipede', 'millipede', 'tick', 'flea', 'louse', 'termite'], 'animals-creatures', 3),
  A(['aviator goggles', 'goggles', 'pith helmet', 'straw hat', 'sun hat', 'wide brim hat', 'brim hat', 'sunglasses', 'optical glasses', 'clubmaster', 'eyeglasses', 'reading glasses', 'tactical uniform', 'camouflage uniform', 'military uniform', 'tunic', 'dwarven clothes', 'medieval tunic', 'pencil case', 'glasses case', 'leather case', 'zippered case', 'suede case', 'work glove', 'exfoliation glove', 'exfoliating glove', 'body glove', 'peeling mitt', 'exfoliation mitt', 'straw hat', 'knight helmet', 'tactical helmet', 'patrol helmet', 'combat helmet'], 'clothing-accessories', 3),
  A(['vise', 'pipe vise', 'bench vise', 'rail puller', 'enerpac', 'rotary cutter', 'fabric cutter', 'garment cutter', 'seam ripper', 'needle threader', 'thread trimmer', 'sewing clipper', 'grinding wheel', 'grout float', 'drain auger', 'washboard', 'bench pin', 'fly fishing reel', 'fishing reel'], 'weapons-tools', 3),
  A(['ciws', 'phalanx', 'naval turret', 'namer', 'armored infantry carrier', 'armored carrier', 'peacekeeper', 'civil defense shelter', 'defense shelter'], 'military-vehicles', 3),
  A(['wrapping machine', 'flow pack', 'packaging machine', 'stick pack', 'foil stick', 'conveyor', 'sortation', 'hydraulic', 'manipulator', 'fueling manipulator', 'robotic fueling', 'high mast', 'lighting pole', 'led pole', 'mast led'], 'industrial-equipment', 3),
  A(['barn', 'farm barn', 'tower bridge', 'london eye', 'big ben', 'taj mahal', 'leaning tower', 'pisa', 'pearl tower', 'oriental pearl', 'sewer', 'brick sewer', 'colonial house', 'brick house', 'dual garage', 'detached garage', 'rock formation', 'split rock', 'al naslaa', 'clock tower', 'gothic tower', 'expressway', 'checkpoint', 'dock shelter', 'loading bay'], 'architecture-landmarks', 3),
  A(['vase', 'porcelain vase', 'marble vase', 'bronze vase', 'decanter', 'pendant light', 'loft pendant', 'ceiling pendant', 'skirting board', 'ceiling plinth', 'ceiling skirting', 'snow globe', 'snowglobe', 'glass globe', 'walking cane', 'walking stick', 'cane', 'pedestal base', 'monumental', 'mobile locker', 'storage rack', 'pallet rack', 'garage storage', 'refrigerated display'], 'furniture-interior', 3),
  A(['dip bar', 'dip rack', 'dip station', 'gymnastic rings', 'training rings', 'exercise mat', 'camping mat', 'sleeping pad', 'yoga mat', 'golden boot', 'trophy', 'cleat trophy', 'messi', 'historical bow', 'recurve bow', 'longbow', 'crossbow'], 'sports-recreation', 3),
  A(['isuzu', 'd-max', 'dmax', 'hilux', 'ranger', 'navara', 'colorado', 'tacoma', 'tundra', 'silverado', 'f-150', 'ram 1500', 'frontier'], 'vehicles', 3),
  A(['snowmobile', 'snowcruiser', 'snowcat', 'sleigh', 'passenger sled', 'snow sled'], 'vehicles', 3),
  A(['icebreaker', 'ocean liner', 'titanic', 'cargo container ship', 'yamal'], 'ships', 3),
  A(['md-11', 'md 11', 'mcdonnell douglas', 'dc-10', 'dc-9', 'md-80', 'md-90'], 'aircraft', 3),
  A(['game controller', 'gamepad', 'joystick', 'xbox controller', 'ps5 controller', 'wireless controller'], 'electronics-gadgets', 3),
  A(['tribal mask', 'mayan mask', 'venetian mask', 'ceremonial mask', 'ritual mask', 'plague doctor', 'tribal'], 'signage-decor', 3),
  A(['speaker', 'soundbar', 'smart speaker', 'floor speaker'], 'electronics-gadgets', 3),
  A(['console organ', 'traditional organ', 'reed organ'], 'musical-instruments', 3),
  A(['cremation', 'incineration', 'crematorium'], 'medical-3d-models', 3),
  A(['lawn mower', 'mower', 'lawnmower'], 'industrial-equipment', 3),
  A(['shrimp', 'shrimps', 'prawn', 'prawns', 'crayfish', 'scampi'], 'food-beverages', 3),
  A(['assault craft', 'combat boat', 'combat craft', 'cb90', 'patrol craft', 'fast craft'], 'ships', 3),
  A(['woman', 'female', 'lady', 'businesswoman'], 'characters-people', 3),
  A(['girl', 'young girl', 'chubby girl', 'fat girl'], 'characters-people', 3),
  A(['boy', 'young boy', 'chubby boy', 'toddler'], 'characters-people', 3),
  A(['aircraft carrier', 'carrier cvn', 'cvn-', 'uss '], 'ships', 3),
  A(['hot dog', 'corn dog', 'hotdog'], 'food-beverages', 3),
  A(['statue', 'sculpture', 'figure', 'idol', 'bust', 'orb gold', 'globus', 'cruciger', 'ceremonial orb'], 'signage-decor', 3),
  A(['mech', 'exosuit', 'mecha', 'biped mech', 'robot'], 'characters-people', 3),
  A(['crab', 'lobster', 'shrimp', 'crayfish', 'prawn'], 'animals-creatures', 3),
  A(['toucan', 'macaw', 'cockatoo', 'parrot', 'owl', 'crow'], 'animals-creatures', 3),
  A(['macaque', 'monkey', 'chimp', 'gorilla', 'baboon', 'lemur', 'primate', 'ape'], 'animals-creatures', 3),
  A(['chipmunk', 'squirrel', 'hamster', 'gerbil', 'beaver', 'marmot'], 'animals-creatures', 3),
  A(['leather bag', 'shabby bag', 'handbag', 'leather organizer'], 'clothing-accessories', 3),
  A(['fireplace', 'fire pit', 'firepit'], 'furniture-interior', 3),
  A(['grill', 'bbq', 'barbecue', 'fire pit'], 'kitchen-tableware', 3),
  A(['waffle', 'ice cream', 'mcsundae', 'gummy', 'soft serve'], 'food-beverages', 3),
  A(['spark plug', 'plug boot', 'plug wire', 'fastener', 'bolt pen'], 'industrial-equipment', 3),
  A(['steamer', 'garment steamer', 'neck fan', 'wearable fan'], 'electronics-gadgets', 3),
  A(['earphone', 'earphones', 'earbuds', 'powerbeats'], 'electronics-gadgets', 3),
  A(['watch', 'wristwatch', 'aquaracer'], 'electronics-gadgets', 3),
  A(['balloon inflator', 'balloon blower', 'blower pump', 'inflator'], 'industrial-equipment', 3),
  A(['container stair', 'stair frame', 'stair system', 'scaffold', 'straddle frame', 'access platform', 'stair and container', 'stair module'], 'industrial-equipment', 3),
  A(['cooling tower', 'rooftop cooling'], 'industrial-equipment', 3),
  A(['bioprinter', 'galvanometer', 'colic relief', 'colic tube'], 'industrial-equipment', 3),
  A(['rolling pin', 'cutting board'], 'kitchen-tableware', 3),
  A(['laundry hamper', 'hamper'], 'furniture-interior', 3),
  A(['magic ring', 'solomon seal', 'seal ring'], 'signage-decor', 3),
  A(['hatchet', 'axe', 'machete'], 'weapons-tools', 3),
  A(['command post', 'defense command', 'military container', 'combat module', 'air defense'], 'military-vehicles', 3),
  A(['uav', 'ucav', 'drone', 'snowgoose', 'dropship'], 'aircraft', 3),
  A(['playing deck', 'card pack', 'playing cards', 'card deck'], 'toys-games', 3),
  A(['recording studio', 'studio interior', 'bath interior', 'arab bath', 'airport terminal', 'terminal complex'], 'architecture-landmarks', 3),
  A(['dhow', 'trolling motor', 'fishing craft'], 'ships', 3),
  A(['tesla', 'battery pack', 'drive unit', 'gearbox', 'automotive frame', 'frame without suspension', 'aero kit'], 'industrial-equipment', 3),
  A(['plane ramp', 'aircraft seat', 'aircraft window', 'aeroplane window'], 'aircraft', 3),
  A(['mount kilimanjaro', 'kilimanjaro', 'mountain'], 'architecture-landmarks', 3),
  A(['falconry hood', 'falcon dummy', 'falcon hood'], 'animals-creatures', 3),
  A(['head with curly', 'boy head', 'girl head', 'curly hair'], 'characters-people', 3),
  A(['anatomical body', 'torso', 'skeleton'], 'characters-people', 3),
  A(['defense pen', 'tactical pen', 'edc pen'], 'industrial-equipment', 3),
  A(['cultural pavilion', 'pavilion'], 'architecture-landmarks', 3),
  A(['slaughterhouse', 'meat processing', 'meat room'], 'architecture-landmarks', 3),
  A(['gullwing', '300sl', 'supra'], 'vehicles', 3),
  A(['hamster', 'duckling', 'guinea pig', 'gerbil', 'ferret'], 'animals-creatures', 3),
  A(['trireme', 'dreadnought', 'amphibious carrier', 'amphibious personnel', 'amphibious armored', 'floating wet'], 'ships', 3),
  A(['kettlebell', 'ball launcher', 'bounce pad', 'launcher with'], 'sports-recreation', 3),
  A(['canine heart', 'heart anatomy', 'distiller', 'endoscopy', 'repellent spray', 'radiant warmer'], 'medical-3d-models', 3),
  A(['biplane', 'ymf-5'], 'aircraft', 3),
  A(['heisenberg', 'crystal tray', 'chemical barrel', 'shard sample', 'crystal'], 'industrial-equipment', 3),
  A(['interstellar', 'tiangong', 'tianhe', 'solar panel', 'propulsion', 'space module', 'main module with solar'], 'space-scifi', 3),
  A(['recon drone', 'stealth drone', 'surveillance drone'], 'aircraft', 3),
  A(['skid steer', 'skid loader', 'radar station', 'radar hangar'], 'industrial-equipment', 3),
  A(['jesus statue', 'statue with', 'stone sculpture', 'funeral urn', 'urn for ashes', 'fertility idol', 'idol statue'], 'signage-decor', 3),
  A(['log seat', 'countryside log', 'log bench'], 'furniture-interior', 3),
  A(['drop tower ride', 'amusement', 'ride lights'], 'architecture-landmarks', 3),
  A(['pixelbloc', 'modular power', 'endoscopy video', 'video processor'], 'electronics-gadgets', 3),
  A(['church organ', 'pipe organ', 'symphonic organ'], 'musical-instruments', 3),
  A(['bunker', 'pillbox'], 'architecture-landmarks', 3),
  A(['greenhouse', 'windcatcher', 'ventilation system', 'gas storage', 'storage tower'], 'industrial-equipment', 3),
  A(['backpack', 'knapsack', 'denim shorts', 'thobe', 'keffiyeh', 'sneakers', 'jewelry case', 'ring case', 'glasses case'], 'clothing-accessories', 3),
  A(['surgical', 'forceps', 'retractor', 'distractor', 'radiant warmer', 'commode', 'shower transfer', 'dust collector', 'pregnancy support', 'exosuit', 'nasal forceps'], 'medical-3d-models', 3),
  A(['terrier', 'labrador', 'retriever', 'puppy', 'cheetah', 'burro', 'leopard'], 'animals-creatures', 3),
  A(['power bank', 'powerbank', 'image sensor', 'cmos', 'altimeter', 'strobe light', 'periscope', 'binocular'], 'electronics-gadgets', 3),
  A(['log bench', 'picnic table', 'garden bench'], 'furniture-interior', 3),
  A(['helicopter', 'chopper', 'rotorcraft', 'gunship helicopter'], 'aircraft', 3),
  A(['fighter jet', 'bomber', 'warplane', 'f-16', 'f-35', 'f-18', 'f-22', 'mig', 'sukhoi', 'stealth aircraft', 'combat aircraft', 'military jet', 'attack aircraft'], 'aircraft', 3),
  A(['cessna', 'piper', 'amphibious plane', 'floatplane', 'private jet', 'business jet', 'light aircraft', 'propeller plane'], 'aircraft', 3),
  A(['biplane', 'vintage plane', 'historic aircraft', 'wwii plane', 'spitfire', 'old aircraft'], 'aircraft', 3),
  A(['airliner', 'airbus', 'boeing', 'passenger plane', 'commercial aircraft', 'jetliner', 'airline', 'atr', 'regional aircraft', 'cargo plane'], 'aircraft', 3),
  A(['airplane', 'aircraft', 'jet plane', 'aeroplane', 'drone aircraft', 'glider', 'seaplane'], 'aircraft', 3),
  A(['galleon', 'sailing ship', 'historic ship', 'tall ship', 'pirate ship', 'old ship', 'wooden ship'], 'ships', 3),
  A(['warship', 'naval ship', 'destroyer', 'battleship', 'submarine', 'aircraft carrier', 'frigate', 'corvette', 'navy vessel', 'patrol boat military'], 'ships', 3),
  A(['cargo ship', 'tanker', 'container ship', 'barge', 'tugboat', 'tug', 'freighter', 'dredger', 'bulk carrier', 'industrial vessel'], 'ships', 3),
  A(['yacht', 'speedboat', 'sailboat', 'kayak', 'canoe', 'cruise ship', 'jet ski', 'catamaran', 'recreational boat', 'fishing boat', 'motorboat', 'dinghy'], 'ships', 3),
  A(['ship', 'boat', 'vessel', 'watercraft', 'ferry', 'hovercraft', 'raft'], 'ships', 3),
  A(['formula 1', 'formula car', 'race car', 'racing car', 'nascar', 'rally car', 'le mans', 'drift car'], 'vehicles', 3),
  A(['ferrari', 'lamborghini', 'porsche', 'supercar', 'sports car', 'mclaren', 'bugatti', 'corvette', 'sport coupe'], 'vehicles', 3),
  A(['suv', 'crossover suv', 'offroad', 'land rover', 'range rover', 'jeep'], 'vehicles', 3),
  A(['rolls royce', 'bentley', 'maybach', 'luxury car', 'limousine', 'limo'], 'vehicles', 3),
  A(['vintage car', 'classic car', 'antique car', 'retro car', 'oldtimer', 'muscle car'], 'vehicles', 3),
  A(['concept car', 'prototype car', 'future car'], 'vehicles', 3),
  A(['car', 'sedan', 'coupe', 'hatchback', 'convertible', 'roadster', 'automobile', 'pickup truck', 'minivan', 'wagon'], 'vehicles', 3),
  A(['truck', 'trailer', 'semi truck', 'semi-truck', 'lorry', 'cargo truck', 'dump truck', 'fire truck', 'tractor truck', 'container mover', 'container shuttle', 'tanker truck', 'flatbed', 'tow truck', 'garbage truck', 'delivery truck'], 'vehicles', 3),
  A(['bus', 'coach bus', 'minibus', 'double decker', 'school bus', 'trolleybus'], 'vehicles', 3),
  A(['train', 'locomotive', 'tram', 'metro', 'subway car', 'railcar', 'railway', 'wagon train', 'freight train'], 'vehicles', 3),
  A(['motorcycle', 'motorbike', 'scooter', 'sidecar', 'chopper bike', 'sport bike', 'dirt bike', 'moped'], 'vehicles', 3),
  A(['bicycle', 'bike', 'cycle', 'mountain bike', 'road bike', 'e-bike', 'tricycle'], 'vehicles', 3),
  A(['military vehicle', 'armored vehicle', 'humvee', 'apc carrier'], 'military-vehicles', 3),
  A(['forklift', 'excavator', 'bulldozer', 'crane truck', 'backhoe', 'loader', 'industrial vehicle', 'tractor', 'harvester'], 'vehicles', 3),
  A(['vehicle', 'transport', 'shuttle', 'wagon', 'cart vehicle', 'atv', 'go kart'], 'vehicles', 3),
  A(['bird', 'parrot', 'owl', 'duck', 'chicken', 'penguin', 'sparrow', 'crow', 'flamingo', 'pigeon', 'rooster'], 'animals-creatures', 3),
  A(['fish', 'shark', 'whale', 'octopus', 'seahorse', 'tuna', 'jellyfish', 'ray fish', 'eel'], 'animals-creatures', 3),
  A(['insect', 'butterfly', 'bee', 'ant', 'wasp', 'dragonfly', 'grasshopper', 'mosquito', 'fly insect'], 'animals-creatures', 3),
  A(['dinosaur', 't-rex', 'triceratops', 'velociraptor', 'stegosaurus', 'dino', 'jurassic'], 'animals-creatures', 3),
  A(['snake', 'lizard', 'crocodile', 'turtle', 'gecko', 'naja', 'reptile', 'iguana', 'chameleon', 'alligator', 'python'], 'animals-creatures', 3),
  A(['dog', 'cat', 'horse', 'cow', 'cattle', 'wolf', 'lion', 'deer', 'elephant', 'corgi', 'rabbit', 'mammal', 'sheep', 'goat', 'pig', 'fox', 'monkey', 'giraffe', 'zebra', 'rhino', 'hippo', 'kangaroo', 'squirrel', 'mouse', 'rat', 'bull', 'buffalo', 'camel', 'donkey', 'llama', 'salt lick', 'terrier', 'labrador', 'retriever', 'puppy', 'poodle', 'bulldog', 'cheetah', 'leopard', 'burro', 'hound', 'beagle', 'chihuahua', 'dachshund', 'husky', 'spaniel', 'collie'], 'animals-creatures', 3),
  A(['animal', 'creature', 'beast', 'pet', 'fur for maya', 'fur for cinema'], 'animals-creatures', 3),
  A(['skeleton', 'anatomy human', 'muscle system', 'body anatomy', 'human body', 'torso anatomy'], 'characters-people', 3),
  A(['child character', 'kid character', 'baby character', 'boy character', 'girl character', 'toddler'], 'characters-people', 3),
  A(['outfit', 'clothing character', 'costume', 'uniform character', 'dress character', 'jacket character', 'apparel', 'denim', 'shorts', 'thobe', 'keffiyeh', 'sneakers', 'knapsack', 'backpack', 'hiking backpack', 'trekking backpack', 'jeans', 'hoodie', 'trousers', 'skirt', 'glasses case', 'embroidered glasses'], 'clothing-accessories', 3),
  A(['elf', 'orc', 'fantasy character', 'goblin', 'knight character', 'wizard', 'warrior', 'dwarf', 'dragon character', 'demon', 'monster character', 'zombie', 'troll', 'barbarian'], 'characters-people', 3),
  A(['robot character', 'cyborg', 'sci-fi character', 'android', 'futuristic soldier', 'space marine', 'mech character'], 'characters-people', 3),
  A(['woman', 'female', 'girl', 'lady', 'businesswoman'], 'characters-people', 3),
  A(['hacker', 'man', 'male', 'person', 'human', 'elderly man', 'player character', 'soldier character', 'guy', 'businessman', 'character'], 'characters-people', 3),
  A(['landmark', 'monument', 'statue exterior', 'eiffel', 'colosseum', 'arch monument', 'memorial'], 'architecture-landmarks', 3),
  A(['skyscraper', 'high rise', 'tower building', 'office tower'], 'architecture-landmarks', 3),
  A(['stadium', 'arena', 'sports venue', 'colosseum stadium'], 'architecture-landmarks', 3),
  A(['street scene', 'road exterior', 'sidewalk', 'crosswalk', 'streetlight', 'alley'], 'architecture-landmarks', 3),
  A(['office building', 'commercial building', 'business center'], 'architecture-landmarks', 3),
  A(['house exterior', 'villa', 'cottage', 'cabin', 'bungalow', 'residential building', 'mansion'], 'architecture-landmarks', 3),
  A(['historic building', 'ancient building', 'ruins', 'castle', 'church', 'cathedral', 'temple building', 'fortress'], 'architecture-landmarks', 3),
  A(['landscape', 'terrain', 'mountain scene', 'park exterior', 'garden exterior', 'nature scene', 'desert scene', 'forest scene'], 'architecture-landmarks', 3),
  A(['factory building', 'warehouse exterior', 'plant exterior', 'industrial building', 'refinery'], 'architecture-landmarks', 3),
  A(['plaza', 'square', 'fountain', 'urban', 'cityscape', 'city block', 'downtown', 'building exterior', 'building'], 'architecture-landmarks', 3),
  A(['bathroom', 'toilet room', 'shower room', 'restroom'], 'furniture-interior', 3),
  A(['bedroom', 'master bedroom'], 'furniture-interior', 3),
  A(['kitchen interior', 'kitchen scene', 'kitchen room'], 'furniture-interior', 3),
  A(['living room', 'lounge interior', 'family room'], 'furniture-interior', 3),
  A(['office interior', 'office room', 'workspace interior', 'meeting room'], 'furniture-interior', 3),
  A(['hall interior', 'hallway', 'corridor', 'lobby'], 'furniture-interior', 3),
  A(['interior scene', 'room interior', 'apartment interior'], 'furniture-interior', 3),
  A(['sofa', 'couch', 'settee', 'loveseat'], 'furniture-interior', 3),
  A(['armchair', 'chair', 'stool', 'bench seat', 'recliner', 'office chair'], 'furniture-interior', 3),
  A(['table', 'desk', 'coffee table', 'dining table', 'nightstand', 'workbench furniture'], 'furniture-interior', 3),
  A(['bed', 'mattress', 'bunk bed', 'crib'], 'furniture-interior', 3),
  A(['lamp', 'chandelier', 'floor lamp', 'table lamp', 'light fixture'], 'lighting', 3),
  A(['cabinet', 'wardrobe', 'shelf', 'bookcase', 'dresser', 'drawer', 'closet', 'sideboard'], 'furniture-interior', 3),
  A(['plate', 'cup', 'mug', 'bowl dish', 'tableware', 'cutlery', 'dishware', 'glassware', 'utensil set'], 'kitchen-tableware', 3),
  A(['refrigerator', 'washing machine', 'dishwasher', 'oven appliance', 'microwave', 'appliance'], 'electronics-gadgets', 3),
  A(['kitchen cabinet', 'kitchen set', 'kitchen counter'], 'kitchen-tableware', 3),
  A(['outdoor furniture', 'patio furniture', 'garden furniture'], 'furniture-interior', 3),
  A(['furniture set', 'furniture'], 'furniture-interior', 3),
  A(['knife', 'axe', 'hammer', 'wrench', 'screwdriver', 'tool', 'drill', 'pliers', 'saw', 'toolbox', 'hand tool'], 'weapons-tools', 3),
  A(['kitchenware', 'pot', 'pan', 'kettle', 'frying pan', 'cookware', 'spatula', 'colander'], 'kitchen-tableware', 3),
  A(['hvac', 'generator', 'pump', 'compressor', 'motor engine', 'turbine', 'industrial machine', 'conveyor', 'machinery', 'cnc', 'robot arm industrial', 'sortation', 'sorter', 'crossbelt', 'cross belt', 'outboard engine', 'v8 engine', 'greenhouse', 'gas storage', 'storage tower', 'windcatcher', 'ventilation system', 'fire starter', 'chimney starter'], 'industrial-equipment', 3),
  A(['bolt', 'gear', 'valve', 'pipe fitting', 'flange', 'industrial part', 'bearing', 'sprocket', 'coupling'], 'industrial-equipment', 3),
  A(['industrial tool', 'power tool', 'grinder', 'welder'], 'industrial-equipment', 3),
  A(['industrial', 'factory equipment', 'warehouse equipment', 'equipment'], 'industrial-equipment', 3),
  A(['pine', 'spruce', 'fir', 'conifer', 'cedar', 'cypress', 'evergreen'], 'nature-plants', 3),
  A(['flower', 'rose', 'tulip', 'daisy', 'sunflower', 'orchid', 'lily', 'blossom'], 'nature-plants', 3),
  A(['grass', 'lawn', 'turf', 'meadow', 'reed'], 'nature-plants', 3),
  A(['leaf', 'foliage', 'branch', 'ivy', 'fern'], 'nature-plants', 3),
  A(['bush', 'shrub', 'hedge'], 'nature-plants', 3),
  A(['pot plant', 'potted plant', 'cactus', 'succulent', 'indoor plant', 'houseplant', 'bonsai'], 'nature-plants', 3),
  A(['tree', 'oak', 'palm tree', 'birch', 'maple', 'willow', 'plant', 'vegetation', 'mushroom', 'herb plant', 'dill', 'basil', 'parsley'], 'nature-plants', 3),
  A(['beverage', 'drink', 'coffee', 'tea', 'wine', 'beer', 'juice', 'cocktail', 'soda', 'smoothie', 'milkshake', 'whiskey', 'champagne', 'water bottle drink'], 'food-beverages', 3),
  A(['fruit', 'apple', 'banana', 'grape', 'strawberry', 'lemon', 'mango', 'pineapple', 'watermelon', 'berry', 'avocado', 'pear'], 'food-beverages', 3),
  A(['vegetable', 'carrot', 'potato', 'tomato', 'onion', 'pepper', 'asparagus', 'broccoli', 'cabbage', 'cucumber', 'lettuce', 'corn', 'garlic', 'pumpkin', 'eggplant', 'spinach'], 'food-beverages', 3),
  A(['food', 'bread', 'cake', 'pizza', 'burger', 'ham', 'sausage', 'pork', 'beef', 'chicken meat', 'meat', 'egg', 'cheese', 'sandwich', 'snack', 'dessert', 'cookie', 'donut', 'pasta', 'sushi', 'steak', 'bacon', 'soup', 'salad', 'seafood', 'lobster', 'shrimp', 'crab food'], 'food-beverages', 3),
  A(['medical', 'hospital', 'surgery', 'implant', 'heart device', 'prosthetic', 'prosthesis', 'syringe', 'stethoscope', 'x-ray', 'mri', 'wheelchair', 'medical device', 'dental', 'anatomy organ', 'cannula', 'pacemaker', 'forceps', 'retractor', 'clamp', 'distractor', 'surgical', 'radiant warmer', 'commode', 'shower seat', 'shower transfer', 'dust collector', 'manicure', 'pregnancy', 'support pillow', 'exosuit', 'nasal', 'cranial', 'infant warmer', 'altimeter'], 'medical-3d-models', 3),
  A(['laboratory', 'lab equipment', 'microscope', 'test tube', 'flask', 'beaker', 'petri', 'centrifuge', 'chemistry'], 'industrial-equipment', 3),
  A(['science', 'scientific', 'research equipment', 'molecule', 'dna model', 'atom'], 'industrial-equipment', 3),
  A(['rifle', 'pistol', 'shotgun', 'sniper rifle', 'firearm', 'machine gun', 'handgun', 'revolver', 'assault rifle', 'ak-47', 'm4', 'gun'], 'weapons-tools', 3),
  A(['sword', 'dagger', 'spear', 'melee weapon', 'katana', 'blade weapon', 'mace', 'battle axe'], 'weapons-tools', 3),
  A(['missile', 'rocket launcher', 'grenade', 'bomb', 'rocketry', 'warhead', 'artillery shell'], 'military-vehicles', 3),
  A(['tank', 'armored tank', 'military vehicle', 'apc', 'armored personnel', 'tactical vehicle', 'tactical missile system'], 'military-vehicles', 3),
  A(['armor', 'helmet military', 'shield', 'military gear', 'body armor', 'tactical vest', 'bulletproof'], 'clothing-accessories', 3),
  A(['soldier', 'military character', 'army man', 'trooper'], 'characters-people', 3),
  A(['military', 'weapon', 'combat gear', 'ammunition', 'ammo'], 'military-vehicles', 3),
  A(['speaker', 'headphone', 'headphones', 'earphone', 'earbuds', 'audio device', 'radio', 'microphone', 'amplifier', 'soundbar', 'subwoofer'], 'electronics-gadgets', 3),
  A(['computer', 'laptop', 'keyboard', 'mouse computer', 'monitor', 'desktop pc', 'pc tower', 'server rack', 'motherboard', 'cpu', 'gpu'], 'electronics-gadgets', 3),
  A(['phone', 'smartphone', 'tablet', 'iphone', 'android phone', 'cellphone', 'mobile phone'], 'electronics-gadgets', 3),
  A(['camera', 'lens', 'bolex', 'dslr', 'camcorder', 'tv', 'television', 'screen monitor', 'projector', 'webcam', 'video camera', 'gopro', 'stroboscope', 'image sensor', 'cmos', 'altimeter', 'strobe light', 'periscope', 'binocular', 'targeting unit'], 'electronics-gadgets', 3),
  A(['electronics', 'device electronic', 'gadget', 'charger', 'router', 'console', 'remote control', 'circuit board', 'power bank', 'powerbank', 'flashlight', 'bug zapper', 'inflator'], 'electronics-gadgets', 3),
  A(['ball', 'football', 'basketball', 'baseball', 'soccer ball', 'tennis racket', 'golf club', 'dumbbell', 'barbell', 'sports equipment', 'helmet sport', 'skateboard', 'ski', 'snowboard', 'bat', 'glove sport'], 'sports-recreation', 3),
  A(['toy', 'doll', 'action figure', 'lego', 'teddy bear', 'plush', 'rubber duck', 'toy car'], 'toys-games', 3),
  A(['board game', 'chess', 'dice', 'playing cards', 'puzzle', 'video game controller', 'arcade'], 'toys-games', 3),
  A(['guitar', 'piano', 'violin', 'drum', 'trumpet', 'musical instrument', 'saxophone', 'flute', 'cello', 'keyboard music'], 'musical-instruments', 3),
  A(['book', 'notebook', 'magazine', 'journal'], 'signage-decor', 3),
  A(['door', 'window frame', 'facade element', 'column', 'arch element', 'dome', 'architectural detail', 'railing', 'staircase', 'balcony', 'gate'], 'signage-decor', 3),
  A(['floor tile', 'parquet', 'flooring', 'tiles'], 'signage-decor', 3),
  A(['wall light architectural', 'sconce', 'ceiling light'], 'signage-decor', 3),
  A(['architectural', 'architecture element', 'molding', 'cornice', 'ornament', 'decoration architectural'], 'signage-decor', 3),
  A(['spaceship', 'spacecraft', 'ufo', 'space shuttle', 'starship', 'alien ship'], 'space-scifi', 3),
  A(['satellite', 'rocket space', 'space station', 'astronaut', 'rover space', 'space probe', 'space rover'], 'space-scifi', 3),
  A(['planet', 'asteroid', 'moon surface', 'mars surface', 'comet'], 'space-scifi', 3),
];

const norm = name => {
  const s = new Set();
  for (const t of (String(name).toLowerCase().match(/[a-z0-9]+/g) || [])) {
    s.add(t);
    if (t.length > 4 && t.endsWith('ies')) s.add(t.slice(0, -3) + 'y');
    if (t.length > 3 && t.endsWith('es')) s.add(t.slice(0, -2));
    if (t.length > 3 && t.endsWith('s')) s.add(t.slice(0, -1));
  }
  return s;
};

// Возвращает слаг категории или null. Молчит при слабом или спорном совпадении —
// лучше оставить в other, чем положить в неверную категорию.
export function portedClassify(name) {
  const low = String(name).toLowerCase(), toks = norm(name), score = {};
  for (const a of PORTED) {
    let hit = 0;
    for (const kw of a.t) {
      if (kw.includes(' ')) { if (low.includes(kw)) hit += a.w; }
      else if (toks.has(kw)) hit += a.w;
    }
    if (hit) score[a.c] = (score[a.c] || 0) + hit;
  }
  const e = Object.entries(score).sort((x, y) => y[1] - x[1]);
  if (!e.length) return null;
  if (e.length > 1 && e[0][1] === e[1][1]) return null;   // ничья — не гадаем
  if (e[0][1] < 3) return null;                            // слабое совпадение — не гадаем
  return e[0][0];
}
